import { Router } from 'express'
import { bdopcionesListaControllers } from '../controller/BdOpcionesListaControllers'

class BdOpcioneslistasRouter {
    public router: Router = Router()

    constructor() {
        this.config();
    }

    config(): void {
        this.router.get('/C2_CAMPO_3', bdopcionesListaControllers.cargarGrupoPoblacional3)
        this.router.get('/C21_CAMPO_22', bdopcionesListaControllers.cargarRadiografiaManosDiagnóstico22)
        this.router.get('/C22_CAMPO_23', bdopcionesListaControllers.cargarRadiografiaPiesDiagnóstico23)
        this.router.get('/C25_CAMPO_26', bdopcionesListaControllers.cargarFactorReumatoideoInicial26)
        this.router.get('/C30_CAMPO_31', bdopcionesListaControllers.cargarParcialOrinaInicial31)
        this.router.get('/C31_CAMPO_32', bdopcionesListaControllers.cargarALTInicial32)
        this.router.get('/C32_CAMPO_33', bdopcionesListaControllers.AntiCCPDiagnóstico33)
        this.router.get('/C33_CAMPO_34', bdopcionesListaControllers.cargarHTADiagnóstico34)
        this.router.get('/C34_CAMPO_35', bdopcionesListaControllers.DMDiagnóstico35)
        this.router.get('/C35_CAMPO_36', bdopcionesListaControllers.cargarECVDiagnóstico36)
        this.router.get('/C36_CAMPO_37', bdopcionesListaControllers.cargarERCDiagnóstico37)
        this.router.get('/C37_CAMPO_38', bdopcionesListaControllers.cargarOsteoporosisDiagnóstico38)
        this.router.get('/C38_CAMPO_39', bdopcionesListaControllers.cargarSindromeSjogrenDiagnóstico39)
        this.router.get('/C40_CAMPO_41', bdopcionesListaControllers.cargarProfesionalRealizóPrimerDAS2841)
        this.router.get('/C45_CAMPO_45_2', bdopcionesListaControllers.cargarAnalgesicosNoOpioidesInicio45_2)
        this.router.get('/C46_CAMPO_45_3', bdopcionesListaControllers.cargarAnalgesicosInicio145_3)
        this.router.get('/C46_CAMPO_45_4', bdopcionesListaControllers.cargarAINESinicio45_4)
        this.router.get('/C46_CAMPO_45_5', bdopcionesListaControllers.cargarCorticoidesInicio45_5)
        this.router.get('/C50_CAMPO_45_7', bdopcionesListaControllers.cargarTamizajeTBantesinicioDMARD145_7)
        this.router.get('/C51_CAMPO_45_8', bdopcionesListaControllers.cargarAntecedentelinfomaantesinicioDMARD45_8)
        this.router.get('/C52_CAMPO_46_1', bdopcionesListaControllers.cargarAzatioprina46_1)
        this.router.get('/C53_CAMPO_46_2', bdopcionesListaControllers.cargarCiclosporina46_2)
        this.router.get('/C54_CAMPO_46_3', bdopcionesListaControllers.cargarCiclofosfamida46_3)
        this.router.get('/C55_CAMPO_46_4', bdopcionesListaControllers.cargarCloroquina46_4)
        this.router.get('/C56_CAMPO_46_5', bdopcionesListaControllers.cargarDpenicilaimina46_5)
        this.router.get('/C57_CAMPO_46_6', bdopcionesListaControllers.cargarEtanercept46_6)
        this.router.get('/C58_CAMPO_46_7', bdopcionesListaControllers.cargarLeflunomida46_7)
        this.router.get('/C59_CAMPO_46_8', bdopcionesListaControllers.cargarMetotrexate46_8)
        this.router.get('/C60_CAMPO_46_9', bdopcionesListaControllers.cargarRituximab46_9)
        this.router.get('/C61_CAMPO_46_10', bdopcionesListaControllers.cargarSulfasalazina46_10)
        this.router.get('/C62_CAMPO_47_1', bdopcionesListaControllers.cargarAbatacept47_1)
        this.router.get('/C63_CAMPO_47_2', bdopcionesListaControllers.cargarAdalimumab_47_2)
        this.router.get('/C64_CAMPO_47_3', bdopcionesListaControllers.cargarCertolizumab47_3)
        this.router.get('/C65_CAMPO_47_4', bdopcionesListaControllers.cargarGolimumab47_4)
        this.router.get('/C66_CAMPO_47_5', bdopcionesListaControllers.cargarHidroxicloroquina47_5)
        this.router.get('/C67_CAMPO_47_6', bdopcionesListaControllers.cargarInfliximab47_6)
        this.router.get('/C68_CAMPO_47_7', bdopcionesListaControllers.cargarSalesdeoro47_7)
        this.router.get('/C69_CAMPO_47_8', bdopcionesListaControllers.cargarTocilizumab47_8)
        this.router.get('/C70_CAMPO_47_9', bdopcionesListaControllers.cargarTofacitinib47_9)
        this.router.get('/C71_CAMPO_47_10', bdopcionesListaControllers.cargarAnakinra47_10)
        this.router.get('/C77_CAMPO_49', bdopcionesListaControllers.cargarRadiografiademanos49)
        this.router.get('/C78_CAMPO_50', bdopcionesListaControllers.cargarRadiografiadepies50)
        this.router.get('/C85_CAMPO_57', bdopcionesListaControllers.cargarParcialdeOrinaúltimosemestre57)
        this.router.get('/C86_CAMPO_58', bdopcionesListaControllers.cargarALTultimosemestre58)
        this.router.get('/C87_CAMPO_59', bdopcionesListaControllers.cargarHTAactual59)
        this.router.get('/C88_CAMPO_60', bdopcionesListaControllers.cargarDMactua60)
        this.router.get('/C89_CAMPO_61', bdopcionesListaControllers.cargarECVactual61)
        this.router.get('/C90_CAMPO_62', bdopcionesListaControllers.cargarERCactual62)
        this.router.get('/C91_CAMPO_63', bdopcionesListaControllers.cargarOsteoporosisactual63)
        this.router.get('/C92_CAMPO_64', bdopcionesListaControllers.cargarSindromeSjogrenactual64)
        this.router.get('/C94_CAMPO_66', bdopcionesListaControllers.cargarProfesionalrealizoultimoDAS28_66)
        this.router.get('/C96_CAMPO_68', bdopcionesListaControllers.cargarEstadoactividadactualdelaARegúnDAS28_68)
        this.router.get('/C99_CAMPO_71_1', bdopcionesListaControllers.cargarAnalgesicosNoOpioides71_1)
        this.router.get('/C100_CAMPO_71_2', bdopcionesListaControllers.cargarAnalgesicosOpioides71_2)
        this.router.get('/C101_CAMPO_71_3', bdopcionesListaControllers.cargarAINES71_3)
        this.router.get('/C102_CAMPO_71_4', bdopcionesListaControllers.cargarCorticoides71_4)
        this.router.get('/C104_CAMPO_71_6', bdopcionesListaControllers.cargarCalcio71_6)
        this.router.get('/C105_CAMPO_71_7', bdopcionesListaControllers.cargarVitaminaD71_7)
        this.router.get('/C107_CAMPO_73_1', bdopcionesListaControllers.cargarAzatioprina73_1)
        this.router.get('/C108_CAMPO_73_2', bdopcionesListaControllers.cargarCiclosporina73_2)
        this.router.get('/C109_CAMPO_73_3', bdopcionesListaControllers.cargarCiclofosfamida73_3)
        this.router.get('/C110_CAMPO_73_4', bdopcionesListaControllers.cargarCorticoides73_4)
        this.router.get('/C111_CAMPO_73_5', bdopcionesListaControllers.cargarDpenicilaimina73_5)
        this.router.get('/C112_CAMPO_73_6', bdopcionesListaControllers.cargarEtanercept73_6)
        this.router.get('/C113_CAMPO_73_7', bdopcionesListaControllers.cargarLeflunomida73_7)
        this.router.get('/C114_CAMPO_73_8', bdopcionesListaControllers.cargarMetotrexate73_8)
        this.router.get('/C115_CAMPO_73_9', bdopcionesListaControllers.cargarRituximab73_9)
        this.router.get('/C116_CAMPO_73_10', bdopcionesListaControllers.cargarSulfasalazina73_10)
        this.router.get('/C117_CAMPO_74_1', bdopcionesListaControllers.cargarAbatacept74_1)
        this.router.get('/C118_CAMPO_74_2', bdopcionesListaControllers.cargarAdalimumab74_2)
        this.router.get('/C119_CAMPO_74_3', bdopcionesListaControllers.cargarCertolizumab74_3)
        this.router.get('/C120_CAMPO_74_4', bdopcionesListaControllers.cargarGolimumab74_4)
        this.router.get('/C121_CAMPO_74_5', bdopcionesListaControllers.cargaHidroxicloroquina74_5)
        this.router.get('/C122_CAMPO_74_6', bdopcionesListaControllers.cargarInfliximab74_6)
        this.router.get('/C123_CAMPO_74_7', bdopcionesListaControllers.cargarSalesdeoro74_7)
        this.router.get('/C124_CAMPO_74_8', bdopcionesListaControllers.cargarTocilizumab74_8)
        this.router.get('/C125_CAMPO_74_9', bdopcionesListaControllers.cargarTofacitinib74_9)
        this.router.get('/C126_CAMPO_74_10', bdopcionesListaControllers.cargarAnakinra74_10)
        this.router.get('/C134_CAMPO_75_4', bdopcionesListaControllers.cargarReemplazoarticular1porAR575_4)
        this.router.get('/C135_CAMPO_75_5', bdopcionesListaControllers.cargarReemplazoarticular2porAR75_5)
        this.router.get('/C136_CAMPO_75_6', bdopcionesListaControllers.cargarReemplazoarticular3porAR75_6)
        this.router.get('/C137_CAMPO_75_7', bdopcionesListaControllers.cargarReemplazoarticula4porAR75_7)
        this.router.get('/C142_CAMPO_80', bdopcionesListaControllers.cargarQuienhacelaatencionclinicaparaAR80)
        this.router.get('/C143_CAMPO_81', bdopcionesListaControllers.cargarNovedaddelpacienterespectoalreporteanterior81)
        this.router.get('/C147_CAMPO_85', bdopcionesListaControllers.cargarCausademuerte85)
    }
}

const bdopcioneslistasRouter = new BdOpcioneslistasRouter()
export default bdopcioneslistasRouter.router